include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - eol_at_end_of_file
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_await_in_return
    - use_key_in_widget_constructors
